[package]
name = "intiface-desktop-egui"
version = "0.1.0"
authors = ["Kyle Machulis <kyle@nonpolynomial.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "intiface-desktop"
path = "src/main.rs"

[dependencies]
buttplug = {version = "5.0.1", default-features = false, features = ["client", "server", "tokio-runtime", "websockets"]}
bytes = "1.0.1"
chrono = "0.4.19"
dashmap = "4.0.2"
dirs = "4.0.0"
eframe = "0.14.0"
futures = "0.3.17"
getset = "0.1.1"
hashbrown = "0.11.2"
indexmap = "1.7.0"
octocrab = "0.12.0"
once_cell = "1.8.0"
parking_lot = "0.11.2"
rand = "0.8.4"
reqwest = "0.11.4"

serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
smartstring = "0.2.9"
thiserror = "1.0.29"
tokio = { version = "1.12.0", features = ["rt-multi-thread", "sync", "macros", "process", "fs", "net"] }
tokio-util = "0.6.8"
tracing = "0.1.28"
tracing-subscriber = "0.2.24"
zip = "0.5.13"

[features]
default = []
http = ["eframe/http"] # Enable if you want to do http requests
persistence = ["eframe/persistence"] # Enable if you want to persist app state on shutdown

[profile.release]
opt-level = 2 # fast and small wasm

[patch.crates-io]

# If you want to use the bleeding edge version of `egui`:
# eframe = { git = "https://github.com/emilk/egui", branch = "master" }

# If you fork https://github.com/emilk/egui you can test with:
# eframe = { path = "../egui/eframe" }
